Update scripts, remove unreachable theories, fix bernstein strategies.

diff --git a/cleanbin-all b/cleanbin-all
--- a/cleanbin-all
+++ b/cleanbin-all
@@ -1,7 +1,4 @@
-#!/bin/bash
-
-# default cleaning mode
-CLEANOPT="--clean-only"
+#!/bin/sh
 
 if [ ! -z "$PVS_DIR" ]; then
     provethem="$PVS_DIR/provethem"
@@ -31,120 +28,43 @@ SYNOPSIS
   cleanbin-all <options>
 
 DESCRIPTION
-  
-  By default, it iterates over all the libraries which are reachable from every 
-  directory mentioned in the PVS_LIBRARY_PATH environment variable. 
+  This script wraps provethem to provide a specific kind of run. By default, it removes 
+  .pvscontext and the binary files from the pvsbin folder in each library listed in the 
+  nasalib.all file.
 
-  A library is considered reachable in a given directory <dir> if it is one of its 
-  direct subfolders and: (1) there is a text file named all-theories in <dir> and
-  the library is mentioned there or (2) there is no such a file in <dir>. The scope 
-  of application of cleanbin-all can be restricted using the options --after, --before,
-  --but, --do, --from, and --to detailed below. The order implicitly referred to by all 
-  these options is the one induced by the applicable all-theories file or the default 
-  order imposed by the operating system, when no all-theories file exists.
+  To supersede this particular configuration, the same options accepted by provethem can
+  be used on this script.
 
-OPTIONS
-  --bin           remove .pvscontext and binary files (default).
-  --all           remove .pvscontext and all files in the pvsbin folders.
-
-  --clearpath     clean the libraries in the current path only
-  --addpath       clean over PVS_LIBRARY_PATH and the current path
-  
-  --after=<dir>   prove all libraries after <dir>, exclusive
-  --before=<dir>  prove all libraries before <dir>, exclusive
-  --but=<dir1>,..,<dirn>  do not process libraries <dir1>,...,<dirn>
-  --do=<dir1>,..,<dirn>   process libraries <dir1>,...,<dirn>
-  --from=<dir>    prove all libraries from <dir>, inclusive.
-  --to=<dir>      prove all libraries to <dir>, inclusive.
-
-  -h|--help       print this message
-  --version       print version information and exit
+  The list of libraries to be processed is read from the file 'all-libraries' if there is no
+  'nasalib.all' file in the current folder.
 
 SEE ALSO
   provethem -- for iterating proveit on a list of directories
 "
 }
 
-ADDITIONALARGS=
-
-while [ $# -gt 0 ]
+for opt in "$@"
 do
-  case $1 in
-    -h|-help|--help)    
+    if [ $opt = "--help" -o $opt = "-help" -o $opt = "-h" ]; then
 	usage
-	exit 0;;
-    -version|--version)     
-	readVersion
-	echo $VERSION
-	exit 0;;
-    --all)
-	CLEANOPT="--clean-all";;
-    --bin)
-	CLEANOPT="--clean-only";;
-    --clearpath)
-	PVS_LIBRARY_PATH=`pwd`;;
-    --addpath)
-	PVS_LIBRARY_PATH=$PVS_LIBRARY_PATH:`pwd`;;
-    # valid options
-    --after=*|-after=*\
-	|--before=*|-before=*\
-	|--but=*|-but=*\
-	|--do=*|-do=*\
-	|--from=*|-from=*\
-	|--to=*|-to=*)
-	ADDITIONALARGS="$ADDITIONALARGS $1";;	
-    --after|-after\
-	|--before|-before\
-	|--but|-but\
-	|--do|-do\
-	|--from|-from\
-	|--to|-to)
-	if [[ $2 == -* ]]; then
-	    if [[ $1 =~ ^-[^-].*$ ]]; then
-		echo "Warning: missing values for $1 option (expected syntax is $1 <values>)"
-	    else
-		echo "Warning: missing values for $1 option (expected syntax is $1=<values>)"
-	    fi;
+	exit 0
+    fi
+done
+
+all_theories_file="nasalib.all"
+if [ ! -f $all_theories_file ]; then 
+    all_theories_file="all-libraries";
+    if [ ! -f $all_theories_file ]; then 
+	all_theories_file="all-theories";
+	if [ -f $all_theories_file ]; then
+	    echo "Warning: all-theories is no longer supported as default input file name, please rename it to all-libraries."
 	else
-	    ADDITIONALARGS="$ADDITIONALARGS $1 $2"
-	    shift
-	fi;;
-    # invalid options
-    *)
-	echo "Warning: omitting unrecognized option $1";;
-  esac
-  shift 
-done 
-
-
-if [ ! -x $provethem ]; then
-    provethem=`which provethem`
+	    echo "Error: input file not found.";
+	    exit 1;
+	fi;
+    fi
 fi
 
-function clean_here {
-    cd $1
-    if [ -f nasalib.all ]; then
-	$provethem $CLEANOPT $ADDITIONALARGS nasalib.all
-    else
-	if ! [ -f all-theories ]; then
-	    # this script assumes that every folder is a pvs library of interest
-	    for i in $(ls -d */); do
-		echo -e ${i%%/};
-	    done >> $1/all-theories
-	    $provethem $CLEANOPT $ADDITIONALARGS all-theories
-	    rm all-theories
-	else
-	    $provethem $CLEANOPT $ADDITIONALARGS all-theories
-	fi;
-    fi;
-}
-
 if [ "$provethem" ]; then
-    while read -d ':' p; do
-	echo -e
-	echo -e "Cleaning '$p' ..."
-	clean_here "`eval echo $p`"	
-    done <<< "$PVS_LIBRARY_PATH:"
-else
-  echo "Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
+  $provethem --action-name="Cleaning" --clean-only "$@" $all_theories_file
 fi
diff --git a/dependency-all b/dependency-all
--- a/dependency-all
+++ b/dependency-all
@@ -30,7 +30,7 @@ SYNOPSIS
 DESCRIPTION
   
   Applies dependencygraph over all the libraries in the current directory that are
-  listed in the all-theories file. 
+  listed in the all-libraries file. 
 
   The option -no-iterate provokes the generation of a graph for the whole collection.
 
@@ -38,13 +38,13 @@ DESCRIPTION
   collection. When in iterative mode, the scope of application can be controlled using 
   the options --after, --before, --but, --do, --from, and --to detailed below. The order 
   implicitly referred to by all these options is the one induced by the applicable 
-  all-theories file.
+  all-libraries file.
 
   This command also accepts all the parameters accepted by dependencygraph.
 
 OPTIONS
 
-  --force         force regeneration of .dep files
+  --dependencies  force regeneration of .dep files
 
   --no-iterate    generate graph for the whole collection instead of
   		  iterating on each library
@@ -83,8 +83,8 @@ do
 	readVersion
 	echo $VERSION
 	exit 0;;
-    -force|--force)
-	FORCE=--force;;
+    -dep|-d|--dependencies)
+	FORCE=--dependencies;;
     --collection-label=*)
 	COLLECTIONLABEL="$COLLECTIONLABEL $1";;
     -no-iterate|--no-iterate)
@@ -126,6 +126,16 @@ do
   shift 
 done
 
+if [ -f all-libraries ]; then
+    INPUT_FILE="all-libraries"
+elif [ -f all-theories ]; then
+    echo "Warning: all-theories is no longer supported as default input file name, please rename it to all-libraries."
+    INPUT_FILE="all-theories"
+else
+    echo "Error: input file not found.";
+    exit 1;
+fi
+
 if [ "$provethem" ]; then
     NASALIBPATH=$(pvs -raw -E '(let ((msg (extra-pvs-nasalib))) (format t "~%NASALIBPATH ~a~%" msg)(bye))' -v 0 -batch | sed -nE 's#NASALIBPATH (.*)/$#\1#p')
     NASALIBDIR=$(echo $NASALIBPATH | sed -nE 's#^.*/([^/]+)$#\1#p')
@@ -133,11 +143,10 @@ if [ "$provethem" ]; then
 	echo "-- Dry run --"
     fi
     if [ "$NOITERATE" ]; then
-	$DRYRUN $NASALIBPATH/dependencygraph $FORCE $COLLECTIONLABEL --svg --rankdir=TB --collection-label="$NASALIBDIR=NASALib" --collection-label="lib=PVS Prelude" --splines=ortho all-theories
+	$DRYRUN $NASALIBPATH/dependencygraph $FORCE $COLLECTIONLABEL --svg --rankdir=TB --collection-label="$NASALIBDIR=NASALib" --collection-label="lib=PVS Prelude" --splines=ortho $INPUT_FILE
     else
-	$DRYRUN $provethem $ADDITIONALARGS --execute "cd ..; $NASALIBPATH/dependencygraph $FORCE $COLLECTIONLABEL $ZOOMORCENTER --svg --rankdir=TB --collection-label=\"$NASALIBDIR=NASALib\" --collection-label=\"lib=PVS Prelude\" --splines=ortho --out=%DIR% $ADDITIONALDGARGS; mv %DIR%.svg %DIR%/"
+	$DRYRUN $provethem $ADDITIONALARGS --execute "$NASALIBPATH/dependencygraph $FORCE $COLLECTIONLABEL $ZOOMORCENTER --svg --rankdir=TB --collection-label=\"$NASALIBDIR=NASALib\" --collection-label=\"lib=PVS Prelude\" --splines=ortho --out=%DIR% $ADDITIONALDGARGS $INPUT_FILE; mv %DIR%.svg %DIR%/" --act="Graphing" $INPUT_FILE
     fi
 else
   echo "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
 fi
-
diff --git a/prove-all b/prove-all
--- a/prove-all
+++ b/prove-all
@@ -29,57 +29,42 @@ DESCRIPTION
   This script wraps provethem to provide a specific kind of run. By default, it removes 
   .pvscontext and the binary files from the pvsbin folder in each library directory, replaces 
   the pvs library path by the current directory, and runs proveit as indicated by the 
-  nasalib.all file. As a side effect, it generates the dependency and tptp files as needed
-  by each library.
+  nasalib.all file.
 
   To supersede this particular configuration, the same options accepted by provethem can
   be used on this script.
 
-OPTIONS
-  prove-all accepts all the provethem options. The only own options are
-
-   -h|--help           print this message
-   --version           print version information and exit
+  The list of libraries to be processed is read from the file 'all-libraries' if there is no
+  'nasalib.all' file in the current folder.
 
 SEE ALSO
   provethem -- for iterating proveit on a list of directories
 "
 }
 
-ADDITIONALARGS=
-CLEANOPT="--clean-only"
-
-while [ $# -gt 0 ]
+for opt in "$@"
 do
-  case $1 in
-    -h|-help|--help)    
+    if [ $opt = "--help" -o $opt = "-help" -o $opt = "-h" ]; then
 	usage
-	exit 0;;
-    -version|--version)     
-	readVersion
-	echo $VERSION
-	exit 0;;
-    --clean|--cleanall)
-	CLEANOPT=$1;;
-    *)
-	ADDITIONALARGS="$ADDITIONALARGS $1";;
-  esac
-  shift 
-done 
+	exit 0
+    fi
+done
 
-all_theories_file="nasalib.all"
-if [ ! -f $all_theories_file ]; then 
-    all_theories_file="all-theories";
-    if [ ! -f $all_theories_file ]; then 
-	echo "Error: $all_theories_file not found.";
-	exit 1;
+all_libraries_file="nasalib.all"
+if [ ! -f $all_libraries_file ]; then 
+    all_libraries_file="all-libraries";
+    if [ ! -f $all_libraries_file ]; then 
+	all_libraries_file="all-theories";
+	if [ -f $all_libraries_file ]; then
+	    echo "Warning: all-theories is no longer supported as default input file name, please rename it to all-libraries."
+	else
+	    echo "Error: input file not found.";
+	    exit 1;
+	fi;
     fi
 fi
 
 if [ "$provethem" ]; then
-    # export PROVEALLVERSION="prove-all $VERSION"
-    $provethem $CLEANOPT $ADDITIONALARGS $all_theories_file
-    $provethem --clearpath --addpath --force $ADDITIONALARGS $all_theories_file
-else
-    echo "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
+    $provethem --clean-only --action-name="Cleaning" "$@" $ADDITIONALARGS $all_libraries_file
+    $provethem --clearpath --addpath --force "$@" $all_libraries_file
 fi
diff --git a/pvs-patches/scripts/proveit b/pvs-patches/scripts/proveit
--- a/pvs-patches/scripts/proveit
+++ b/pvs-patches/scripts/proveit
@@ -12,6 +12,9 @@
 # is claimed in the United States under Title 17, U.S.Code. All Other
 # Rights Reserved.
 #
+# Mariano Moscato (04/26/2021)
+# National Institute of Aerospace
+#
 # Script for batch proving in PVS 
 #  
 
@@ -28,15 +31,15 @@ readVersion() {
     fi
 }
 
-# Extension for proof status summary file
-EXT=.summary
 
-# PVS directory of binary files
-PVSBIN=pvsbin
+EXT=.summary # Extension for proof status summary file
+
+PVSBIN=pvsbin # PVS directory of binary files
 LISPFORCE=t
 LISPIMPORT=nil
 LISPSCRIPTS=t
 LISPWRITESCRIPTS=nil
+LISPAUTOTOP=nil
 LISPTRACES=nil
 LISPTXTPROOFS=nil
 LISPTEXPROOFS=nil
@@ -85,7 +88,7 @@ all_opt() {
     fi
     LISPIMPORT=t
     LISPSCRIPTS=nil
-    LISPDEPENDENCIES=t
+    LISPDEPENDENCIES=relative
   fi
 }
 
@@ -99,15 +102,15 @@ compile_infile_name() {
   if [ -d $ARG ]; then
     PVSCONTEXT=$ARG
     if [ -z "$OUTFILE" ]; then
-      OUTFILE=$ARG$EXT
+	OUTFILE=$ARG$EXT
     fi
     PVSFILE=`basename $TOP .pvs`
-    if [ -f $PVSCONTEXT/$PVSFILE.pvs ]; then
+    if [ -f $PVSCONTEXT/$PVSFILE.pvs -o "$LISPAUTOTOP" = "t" ]; then
 	all_opt
     else
 	FILENOTFOUND="$PVSCONTEXT/$PVSFILE.pvs"
     fi
-    LISPDEPENDENCIES=t
+    LISPDEPENDENCIES=relative
   # If  <file>, set context to its dirname and pvsfile to its base name
   else
     PVSCONTEXT=$(cd "$(dirname $ARG)"; pwd -P)
@@ -134,9 +137,9 @@ compile_infile_name() {
 		    exit 1
 		fi;;
 	    *)  FILENOTFOUND="$PVSCONTEXT/$PVSFILE.pvs"
-		if [ -z "$NOFILE" ]; then
+		if [ -z "$NOFILE" -a "$LISPAUTOTOP" != "t" ]; then
 		    echo "Error: File $FILENOTFOUND not found"
-		    exit;
+		    exit 1;
 		fi;;
 	esac
     fi
@@ -166,11 +169,12 @@ compile_outfile_names() {
     if [ "$BASEOUT" = $base ]; then
       base=$BASEOUT$EXT
     fi
-    OUTFILE=$dir/$base
-    LOGFILE=$dir/$BASEOUT.log
+    if [ "$dir" ]; then
+	OUTFILE=$dir/$base
+	LOGFILE=$dir/$BASEOUT.log
+    fi
     if [ "$LISPTYPECHECK" = "t" ]; then 
 	OUTFILE=$OUTFILE-tc
-	LOGFILE=$LOGFILE
     fi
 }
 
@@ -206,18 +210,10 @@ cleanup() {
 	  fi
       fi   
       if [ "$LOGFILE" ]; then
-	  if [ "$OUTDIR" ]; then
-	      LOGFILE_RELATIVE_PATH="$OUTDIR/$LOGFILE"
-	  else 
-	      LOGFILE_RELATIVE_PATH="$LOGFILE"
-	  fi
+	  LOGFILE_RELATIVE_PATH="$LOGFILE"
       fi
       if [ "$OUTFILE" ]; then
-	  if [ "$OUTDIR" ]; then
-	      OUTFILE_RELATIVE_PATH="$OUTDIR/OUTFILE"
-	  else 
-	      OUTFILE_RELATIVE_PATH="$OUTFILE"
-	  fi
+	  OUTFILE_RELATIVE_PATH="$OUTFILE"
       fi
       if [ -z "$QUIET" ]
       then
@@ -279,7 +275,8 @@ OPTIONS
    --clean-all         just remove .pvscontext and all files in the pvsbin folder 
                        (do not typecheck nor prove)
    -d|--dir <dir>      use <dir> as default directory of summary files
-   --dependencies      compute theory dependencies and save them in pvsbin/<file>.dep.
+   --dependencies [relative|fullpath]  compute theory dependencies and save them in 
+                       pvsbin/<file>.dep. 
    --default-script <proof script> default prooflite script to be tried on unfinished branches
    --disable <o1,..,on> disable external oracles o1,...,on
    --disable-oracles   disable any external oracle
@@ -304,6 +301,7 @@ OPTIONS
    --txt               generate text proof files in directory pvstxt
    --no-txt            don't generate text proof files (default)
    -t|--top <topfile>  use <topfile>.pvs instead of top.pvs when the input is a directory
+   --generate-top      generate top file if it does not exist
    --timeout <secs>    timeout in seconds for each proof
    --traces            include proof traces in log file
    --no-traces         don't include proof traces in log file (default)
@@ -323,7 +321,7 @@ error_output() {
     sed -i.bak -n -e '/^<pvserror/,/^<\/pvserror/p'\
 	-e '/^Restored .*/d'\
 	-e '/^\*\*\* /p'\
-	-e '/^Typechecking/h'\
+	-e '/^Error/p'\
 	-e '/^Typechecking/ !{
                  /^Typecheck error/ {
                    p;g;p
@@ -333,16 +331,32 @@ error_output() {
                    /^PVS file .* is not/!H
                  }
               }'\
+	-e '/^Typechecking/h'\
 	-e '/Proof summary/,/Grand Totals/p' $OUTFILE 
     if [ -z "$QUIET" ]; then
 	cat $OUTFILE | \
-	    sed -e "s+^<pvserror msg=\"\(.*\)\">+\1 ($ARG)+" \
-            -e 's/"//g' -e '/^<\/pvserror>/d' \
+	    sed -e "s+^<pvserror msg=\"\(.*\)\">+Error: \1 ($ARG) +" \
+            -e 's/"//g' -e 's/<\/pvserror>//g' \
+	    -e 's/^Error/*** Error/gp'\
+	    -e 's/^\*\*\* Warning/*** Warning/gp'\
 	    -e '/^\*\*\*.*/d' 
     else
 	cat $OUTFILE | \
-	    sed -n -e "s+^<pvserror msg=\"\(.*\)\">+\1 ($ARG)+p" \
-                   -e "s/^\"\(.*\)\"$/\1/p" -e "/^Typecheck error/p"
+	    sed -n -e "s+^<pvserror msg=\"\(.*\)\">\"\(.*\)\"<\/pvserror>+Error: \1 ($ARG) \2 +p" \
+		-e 's/^Error/*** Error/gp'\
+		-e 's/^\*\*\* Warning/*** Warning/gp'\
+		-e "/^Typecheck error/p" \
+		-e '/Proof summary/h'\
+               -e '/Proof summary/ !{
+                    /unfinished/H
+                    /unchecked/H
+                    /untried/H
+                   }'\
+               -e '/Theory totals/ {
+                   H;g
+                   /\.\.\.\./p
+                  }'\
+               -e '/^Grand Totals:/p'
     fi
     if [ "$LOG" ]; then
 	mv -f $OUTFILE.bak $LOGFILE
@@ -355,6 +369,7 @@ error_output() {
 pvs_output() {
     sed -i.bak -n -e '/File .*\.pvs typechecked/p'\
         -e '/^\*\*\* /p'\
+	-e '/^Error/p'\
         -e '/Proof summary/,/Grand Totals/p' $OUTFILE
     cat $OUTFILE | quiet_output
     if [ "$LOG" ]; then
@@ -366,9 +381,11 @@ pvs_output() {
 
 # quiet output
 quiet_output() {
-    if [ -z "$QUIET" ]
+    if [ -z "$QUIET" ] || [ "$LISPTYPECHECK" = "t" ]
     then
 	sed -n -e '/File/p'\
+	       -e '/Warning/p'\
+	       -e '/Error/p'\
                -e '/Proof summary/h'\
                -e '/Proof summary/ !{
                     /unfinished/H
@@ -387,6 +404,8 @@ quiet_output() {
                   }'
     else
 	sed -n -e '/Proof summary/h'\
+	       -e '/Warning/p'\
+	       -e '/Error/p'\
                -e '/Proof summary/ !{
                     /unfinished/H
                     /unchecked/H
@@ -410,8 +429,6 @@ process_opts() {
 	    CLEAN=yes;;
         ~c|-no-clean|--no-clean)
 	    CLEAN=;;
-        -dep|--dep|-dependencies|--dependencies)
-	    LISPDEPENDENCIES=t;;
 	-f|-force|--force)   
 	    LISPFORCE=t;;
 	~f|-no-force|--no-force)   
@@ -453,7 +470,6 @@ process_opts() {
 	-v|-verbose|--verbose)
 	    QUIET=;;
 	--*)           
-	    usage
 	    echo "Error: $1 is not a valid option"
 	    exit 1;;
 	-*)
@@ -535,7 +551,7 @@ proveit() {
       compile_outfile_names
       cleanup
       
-      if [ "$FILENOTFOUND" ]; then
+      if [ "$FILENOTFOUND" -a "$LISPAUTOTOP" != "t" ]; then
 	  if [ -z "$CLEAN" ]; then
 	      echo "Error: File $FILENOTFOUND not found"
 	  fi
@@ -563,15 +579,18 @@ proveit() {
 	  if [ "$LISPIMPORT" = "t" ]; then
 	      echo "Proving chain of imported theories"
 	  fi 
-	  if [ "$LISPDEPENDENCIES" ]; then
-	      echo "Saving theory dependencies in directory pvsbin"
+	  if [ "$LISPDEPENDENCIES" != "nil" ]; then
+	      echo "Saving theory dependencies ($LISPDEPENDENCIES) in directory pvsbin"
 	  fi
 	  if [ "$LISPSCRIPTS" != "t" ]; then
 	      echo "ProofLite scripts won't be installed"
 	  fi 
 	  if [ "$LISPWRITESCRIPTS" = "t" ]; then
-	      echo "Proofs will be stored as ProofLite scripts in .prl files."
+	      echo "Proofs wish/ill be stored as ProofLite scripts in .prl files."
 	  fi 
+	  if [ "$LISPAUTOTOP" = "t" ]; then
+	      echo "Top file will be automatically generated."
+	  fi
 	  if [ "$LISPFORCE" != "t" ]; then
 	      echo "Proofs won't be forced"
 	  fi
@@ -600,7 +619,7 @@ proveit() {
 
       export PROVEITARG="$ARG"
       export PROVEITPVSCONTEXT="$PVSCONTEXT"
-      if [ -f $PVSCONTEXT/$PVSFILE.pvs ]; then
+      if [ -f $PVSCONTEXT/$PVSFILE.pvs -o "$LISPAUTOTOP" = "t" ]; then
 	  export PROVEITPVSFILE="$PVSFILE"
       else
  	  export PROVEITPVSFILE=""
@@ -610,6 +629,7 @@ proveit() {
       export PROVEITLISPWRITESCRIPTS="$LISPWRITESCRIPTS"
       export PROVEITLISPTRACES="$LISPTRACES"
       export PROVEITLISPFORCE="$LISPFORCE"
+      export PROVEITLISPAUTOTOP="$LISPAUTOTOP"
       export PROVEITLISPTYPECHECK="$LISPTYPECHECK"
       export PROVEITLISPTXTPROOFS="$LISPTXTPROOFS"
       export PROVEITLISPTEXPROOFS="$LISPTEXPROOFS"
@@ -625,6 +645,7 @@ proveit() {
       
       if [ "$DEBUG" ]; then
 	  readVersion
+	  echo "QUIET: $QUIET"
 	  echo "PROVEITVERSION: $VERSION"
 	  echo "OUTFILE: $OUTFILE"
 	  echo "LOGFILE: $LOGFILE"
@@ -636,6 +657,7 @@ proveit() {
 	  echo "PROVEITLISPWRITESCRIPTS: $PROVEITLISPWRITESCRIPTS"
 	  echo "PROVEITLISPTRACES: $PROVEITLISPTRACES"
 	  echo "PROVEITLISPFORCE: $PROVEITLISPFORCE" 
+	  echo "PROVEITLISPAUTOTOP: $LISPAUTOTOP"
 	  echo "PROVEITLISPTYPECHECK: $PROVEITLISPTYPECHECK"
 	  echo "PROVEITLISPTXTPROOFS: $PROVEITLISPTXTPROOFS"
 	  echo "PROVEITLISPTEXPROOFS: $PROVEITLISPTEXPROOFS"
@@ -652,24 +674,26 @@ proveit() {
 
       if [ $PVSTIMEOUT ]; then
 	  $PVSPATH/pvs -raw $PVSLISP -timeout $PVSTIMEOUT -E "(proveit)" > $OUTFILE
+	  ret_value=$?
       else
 	  $PVSPATH/pvs -raw $PVSLISP -E "(proveit)" > $OUTFILE
+	  ret_value=$?
       fi
 
-      PVSRESULT=$?
-      grep pvserror $OUTFILE > /dev/null
-      ERRORRESULT=$?
-      if [ $ERRORRESULT -eq 0 -o $PVSRESULT -ne 0 ]; then
+      if [ $ret_value -ne 0 ]; then
 	  error_output
-	  exit 1
+	  exit $ret_value 
       fi
       pvs_output
   fi
   reset_vars
+  return $ret_value;
 }
 
 # ... and go!
 #
+
+ret_value=0
 
 reset_vars
 while [ $# -gt 0 ]
@@ -717,6 +741,8 @@ do
     -t|-top|--top)           
 	  TOP=$2
 	  shift;;
+    -generate-top|--generate-top)           
+	  LISPAUTOTOP=t;;
     -Clean|--Clean)
 	echo "The option $1 is not longer supported. Please use --clean-all instead."
 	exit 1;;
@@ -756,6 +782,20 @@ do
 	    LISPAUTOFIX=$2
 	    shift
 	fi;;
+    -dep|--dep|-dependencies|--dependencies)
+	if echo $2 | grep -qE '^-.*$'; then
+	    # 'relative' by default
+	    LISPDEPENDENCIES=relative
+	elif echo $2 | grep -qE '^relative$'; then
+	    LISPDEPENDENCIES=relative
+	    shift
+	elif echo $2 | grep -qE '^fullpath$'; then
+	    LISPDEPENDENCIES=fullpath
+	    shift
+	else
+	    echo "Error: --dependencies option must be followed by the options 'relative' or 'fullpath'. (See proveit --help for details.)"
+	    exit 1
+	fi;;
     --timeout)
 	if echo $2 | grep -qE '^[0-9]+$'; then
 	    PVSTIMEOUT=$2
@@ -776,16 +816,19 @@ do
     *)     ARG=$1
  	   NOFILE=
            proveit
+	   ret_value=$?
   esac
   shift 
 done 
 if [ "$NOFILE" ]; then
   ARG=$TOP.pvs
   if [ -f $ARG -o "$CLEAN" = "only" ]; then
-    proveit
+      proveit
+      ret_value=$?
   else
-    usage
+      echo "[proveit] no file '$NOFILE'"
+      usage
   fi
 fi
 
-exit 0
+exit $ret_value;
diff --git a/typecheck-all b/typecheck-all
--- a/typecheck-all
+++ b/typecheck-all
@@ -28,101 +28,45 @@ SYNOPSIS
   typecheck-all <options>
 
 DESCRIPTION
-  
-  Uses provethem to typecheck all the libraries in the current directory. 
+  This script wraps provethem to provide a specific kind of run. By default, it removes 
+  .pvscontext and the binary files from the pvsbin folder in each library directory, replaces 
+  the pvs library path by the current directory, and typechecks the libraries listed in the 
+  nasalib.all file. 
 
-  As in provethem, the scope of application can be controlled using 
-  the options --after, --before, --but, --do, --from, and --to detailed below. The order 
-  implicitly referred to by all these options is the one induced by the applicable 
-  all-theories file.
+  To supersede this particular configuration, the same options accepted by provethem can
+  be used on this script.
 
-OPTIONS
-
-  --after=<dir>           typecheck all libraries after <dir>, exclusive
-  --before=<dir>          typecheck all libraries before <dir>, exclusive
-  --but=<dir1>,..,<dirn>  do not typecheck libraries <dir1>,...,<dirn>
-  --dir <dir>             use <dir> as default directory of summary files
-  --do=<dir1>,..,<dirn>   typecheck libraries <dir1>,...,<dirn>
-  --ext <ext>             use <ext> as default extension of summary files
-  --from=<dir>            prove all libraries from <dir>, inclusive.
-  --log                   log all information generated by PVS in <file>.log 
-  --out <outfile>         save output to <outfile>
-  --to=<dir>              typecheck all libraries to <dir>, inclusive.
-  --top <th>              use <th>.pvs instead of top.pvs as top theory  
-  --verbose               print summary information for all theories
-
-  -h|--help               print this message
-  --version               print version information and exit
+  The list of libraries to be processed is read from the file 'all-libraries' if there is no
+  'nasalib.all' file in the current folder.
 
 SEE ALSO
-  provethem -- for iterating commands on a list of directories
+  provethem -- for iterating proveit on a list of directories
 "
 }
 
-ADDITIONALARGS=
-
-while [ $# -gt 0 ]
+for opt in "$@"
 do
-  case $1 in
-    -h|-help|--help) 
+    if [ $opt = "--help" -o $opt = "-help" -o $opt = "-h" ]; then
 	usage
-	exit 0;;
-    -version|--version)
-	readVersion
-	echo $VERSION
-	exit 0;;
-    -force|--force)
-	FORCE=--force;;
-    # valid options
-    --after=*|-after=*\
-	|--before=*|-before=*\
-	|--but=*|-but=*\
-	|--do=*|-do=*\
-	|--from=*|-from=*\
-	|--to=*|-to=*\
-	|--log\
-	|--verbose)
-	ADDITIONALARGS="$ADDITIONALARGS $1";;	
-    --after|-after\
-	|--before|-before\
-	|--but|-but\
-	|--do|-do\
-	|--from|-from\
-	|--to|-to\
-	|--dir|-dir\
-	|--ext|-ext\
-	|--out|-out\
-	|--top|-top)
-	if [[ $2 == -* ]]; then
-	    if [[ $1 =~ ^-[^-].*$ ]]; then
-		echo "Warning: missing values for $1 option (expected syntax is $1 <values>)"
-	    else
-		echo "Warning: missing values for $1 option (expected syntax is $1=<values>)"
-	    fi;
-	else
-	    ADDITIONALARGS="$ADDITIONALARGS $1 $2"
-	    shift
-	fi;;
-    # invalid options
-    *)
-	echo "Warning: omitting unrecognized option $1";;
-  esac
-  shift 
+	exit 0
+    fi
 done
 
 all_theories_file="nasalib.all"
 if [ ! -f $all_theories_file ]; then 
-    all_theories_file="all-theories";
+    all_theories_file="all-libraries";
     if [ ! -f $all_theories_file ]; then 
-	echo "Error: $all_theories_file not found.";
-	exit 1;
+	all_theories_file="all-theories";
+	if [ -f $all_theories_file ]; then
+	    echo "Warning: all-theories is no longer supported as default input file name, please rename it to all-libraries."
+	else
+	    echo "Error: input file not found.";
+	    exit 1;
+	fi;
     fi
 fi
 
 if [ "$provethem" ]; then
-  $provethem --clean-only $* $all_theories_file
-  $provethem  $ADDITIONALARGS --clearpath --addpath --typecheck $* $all_theories_file
-else
-  echo "Directory where PVS is installed must be in the environment variable PATH for this command to work"
+  $provethem --clean-only --action-name="Cleaning" "$@" $all_theories_file
+  $provethem  --action-name="Typechecking" --clearpath --addpath --force --typecheck "$@" $all_theories_file
 fi
-
