Update version in *-all scripts

diff --git a/cleanbin-all b/cleanbin-all
--- a/cleanbin-all
+++ b/cleanbin-all
@@ -1,20 +1,30 @@
 #!/bin/bash
 
-VERSION="ProofLite-7.0.0 (05/06/20)"
-CLEANBINALLVERSION="cleanbin-all - $VERSION"
+# default cleaning mode
+CLEANOPT="--clean-only"
 
 if [ ! -z "$PVS_DIR" ]; then
     provethem="$PVS_DIR/provethem"
 else
-    provethem="provethem"
+    provethem=`which provethem`
+    if [ ! $provethem  ]; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
 fi
 
-# default cleaning mode
-CLEANOPT="--clean-only"
+readVersion() {
+    if ! type "$provethem" > /dev/null 2>&1  || ! VERSION=$($provethem --version) ; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
+}
 
 usage() {
+    readVersion
+    
     echo "NAME
-  $CLEANBINALLVERSION -- Clean .pvscontext and binary files from PVS libraries.
+  cleanbin-all $VERSION -- Clean .pvscontext and binary files from PVS libraries.
 
 SYNOPSIS
 
@@ -64,7 +74,8 @@ do
 	usage
 	exit 0;;
     -version|--version)     
-	echo $CLEANBINALLVERSION
+	readVersion
+	echo $VERSION
 	exit 0;;
     --all)
 	CLEANOPT="--clean-all";;
diff --git a/dependency-all b/dependency-all
--- a/dependency-all
+++ b/dependency-all
@@ -1,11 +1,27 @@
 #!/bin/bash
 
-VERSION="ProofLite-7.1.0 (06/01/20)"
-DEPENDENCYALLVERSION="dependency-all - $VERSION"
+if [ ! -z "$PVS_DIR" ]; then
+    provethem="$PVS_DIR/provethem"
+else
+    provethem=`which provethem`
+    if [ ! $provethem  ]; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
+fi
+
+readVersion() {
+    if ! type "$provethem" > /dev/null 2>&1  || ! VERSION=$($provethem --version) ; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
+}
 
 usage() {
+    readVersion
+    
     echo "NAME
-  $DEPENDENCYALLVERSION -- Generates the dependency graphs for the PVS libraries in the current folder.
+  dependency-all $VERSION -- Generates the dependency graphs for the PVS libraries in the current folder.
 
 SYNOPSIS
 
@@ -48,10 +64,13 @@ do
 	usage
 	exit 0;;
     -version|--version)
-	echo $DEPENDENCYALLVERSION
+	readVersion
+	echo $VERSION
 	exit 0;;
     -force|--force)
 	FORCE=--force;;
+    --collection-label=*)
+	COLLECTIONLABEL="$COLLECTIONLABEL $1";;
     # valid options
     --after=*|-after=*\
 	|--before=*|-before=*\
@@ -83,13 +102,11 @@ do
   shift 
 done
 
-provethem=`which provethem`
-
 if [ "$provethem" ]; then
-    NASALIBPATH=$(pvs -raw -E '(let ((msg (extra-pvs-nasalib))) (format t "~%NASALIBPATH ~a~%" msg)(bye))' -v 0 -batch | sed -nE 's#NASALIBPATH (.*)$#\1#p')
-    NASALIBDIR=$(echo $NASALIBPATH | sed -nE 's#^.*/([^/]+)/$#\1#p')
-    $provethem $ADDITIONALARGS --execute "cd $NASALIBPATH; ./dependencygraph $FORCE --centered-in=%DIR% --svg --rankdir=TB --collection-label=\"$NASALIBDIR=NASALib\" --collection-label=\"lib=PVS Prelude\" --splines=ortho --out=%DIR%; mv %DIR%.svg %DIR%/"
+    NASALIBPATH=$(pvs -raw -E '(let ((msg (extra-pvs-nasalib))) (format t "~%NASALIBPATH ~a~%" msg)(bye))' -v 0 -batch | sed -nE 's#NASALIBPATH (.*)/$#\1#p')
+    NASALIBDIR=$(echo $NASALIBPATH | sed -nE 's#^.*/([^/]+)$#\1#p')
+    $provethem $ADDITIONALARGS --execute "cd ..; pwd -P; $NASALIBPATH/dependencygraph $FORCE $COLLECTIONLABEL --centered-in=%DIR% --svg --rankdir=TB --collection-label=\"$NASALIBDIR=NASALib\" --collection-label=\"lib=PVS Prelude\" --splines=ortho --out=%DIR%; mv %DIR%.svg %DIR%/"
 else
-  echo "Error: directory where PVS is installed must be in the environment variable PATH for this command to work"
+  echo "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
 fi
 
diff --git a/prove-all b/prove-all
--- a/prove-all
+++ b/prove-all
@@ -1,12 +1,25 @@
 #!/bin/sh
 
-VERSION="ProofLite-7.0.0 (04/21/20)"
+if [ ! -z "$PVS_DIR" ]; then
+    provethem="$PVS_DIR/provethem"
+else
+    provethem=`which provethem`
+    if [ ! $provethem  ]; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
+fi
 
-export PROVEALLVERSION="prove-all - $VERSION"
+readVersion() {
+    if ! type "$provethem" > /dev/null 2>&1  || ! VERSION=$($provethem --version) ; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
+}
 
 usage() {
     echo "NAME
-  $PROVEALLVERSION -- runs proveit on all the libraries in the NASALib
+  prove-all $VERSION -- runs proveit on all the libraries in the NASALib
 
 SYNOPSIS
 
@@ -43,7 +56,8 @@ do
 	usage
 	exit 0;;
     -version|--version)     
-	echo $PROVEALLVERSION
+	readVersion
+	echo $VERSION
 	exit 0;;
     --clean|--cleanall)
 	CLEANOPT=$1;;
@@ -53,17 +67,19 @@ do
   shift 
 done 
 
-[ ! -f nasalib.all ] && { echo "Error: nasalib.all not found."; exit 1;}
-
-provethem="../provethem"
-
-if [ ! -x $provethem ]; then
-    provethem=`which provethem`
+all_theories_file="nasalib.all"
+if [ ! -f $all_theories_file ]; then 
+    all_theories_file="all-theories";
+    if [ ! -f $all_theories_file ]; then 
+	echo "Error: $all_theories_file not found.";
+	exit 1;
+    fi
 fi
 
 if [ "$provethem" ]; then
-  $provethem $CLEANOPT $ADDITIONALARGS nasalib.all
-  $provethem --clearpath --addpath --force $ADDITIONALARGS nasalib.all
+    # export PROVEALLVERSION="prove-all $VERSION"
+    $provethem $CLEANOPT $ADDITIONALARGS $all_theories_file
+    $provethem --clearpath --addpath --force $ADDITIONALARGS $all_theories_file
 else
-  echo "Error: directory where PVS is installed must be in the environment variable PATH for this command to work"
+    echo "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
 fi
diff --git a/typecheck-all b/typecheck-all
--- a/typecheck-all
+++ b/typecheck-all
@@ -1,11 +1,27 @@
-provethem="../provethem"
+#!/bin/sh
 
-VERSION="ProofLite-7.1.0 (06/01/20)"
-TYPECHECKALLVERSION="typecheck-all - $VERSION"
+if [ ! -z "$PVS_DIR" ]; then
+    provethem="$PVS_DIR/provethem"
+else
+    provethem=`which provethem`
+    if [ ! $provethem  ]; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
+fi
+
+readVersion() {
+    if ! type "$provethem" > /dev/null 2>&1  || ! VERSION=$($provethem --version) ; then
+	printf "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH.\n"
+	exit 1;
+    fi
+}
 
 usage() {
+    readVersion
+    
     echo "NAME
-  $TYPECHECKALLVERSION -- Typechecks the PVS libraries in the current folder.
+  typecheck-all $VERSION -- Typechecks the PVS libraries in the current folder.
 
 SYNOPSIS
 
@@ -52,7 +68,8 @@ do
 	usage
 	exit 0;;
     -version|--version)
-	echo $TYPECHECKALLVERSION
+	readVersion
+	echo $VERSION
 	exit 0;;
     -force|--force)
 	FORCE=--force;;
@@ -93,13 +110,18 @@ do
   shift 
 done
 
-if [ ! -x $provethem ]; then
-    provethem=`which provethem`
+all_theories_file="nasalib.all"
+if [ ! -f $all_theories_file ]; then 
+    all_theories_file="all-theories";
+    if [ ! -f $all_theories_file ]; then 
+	echo "Error: $all_theories_file not found.";
+	exit 1;
+    fi
 fi
 
 if [ "$provethem" ]; then
-  $provethem --clean-only $* nasalib.all
-  $provethem  $ADDITIONALARGS --clearpath --addpath --typecheck $* nasalib.all
+  $provethem --clean-only $* $all_theories_file
+  $provethem  $ADDITIONALARGS --clearpath --addpath --typecheck $* $all_theories_file
 else
   echo "Directory where PVS is installed must be in the environment variable PATH for this command to work"
 fi
