Added summaries, etc

diff --git a/dependency-all b/dependency-all
--- a/dependency-all
+++ b/dependency-all
@@ -70,7 +70,7 @@ SEE ALSO
 ADDITIONALARGS=
 NOITERATE=
 DRYRUN=
-ZOOMORCENTER="--centered-at=%DIR%"
+ZOOMORCENTER="--centered-at='%DIR%'"
 
 while [ $# -gt 0 ]
 do
@@ -92,7 +92,7 @@ do
 	DRYRUN="--dry-run";;
     -zoomed|--zoomed)
 	ZOOMED=t
-	ZOOMORCENTER="--do=%DIR% --zoom=%DIR%";;
+	ZOOMORCENTER="--do='%DIR%' --zoom='%DIR%'";;
     # valid options
     --after=*|-after=*\
     	|--before=*|-before=*\
@@ -139,7 +139,8 @@ else
 fi
 
 if [ "$provethem" ]; then
-    NASALIBPATH=$(pvs -raw -E '(let ((msg (nasalib-path))) (format t "~%NASALIBPATH ~a~%" msg)(bye))' -v 0 -batch | sed -nE 's#NASALIBPATH (.*)/$#\1#p')
+    NASALIBPATH=`./pvs-scripts/find-pvslib NASALib --strict --format "<dir>"`
+    ( [ -z $PVS_LIBRARY_PATH ] || [ ! -d $NASALIBPATH ] ) && echo "Cannot find NASALib path" && exit 1;
     NASALIBDIR=$(echo $NASALIBPATH | sed -nE 's#^.*/([^/]+)$#\1#p')
     if [ $DRYRUN ]; then
 	echo "-- Dry run --"
@@ -152,11 +153,11 @@ if [ "$provethem" ]; then
 	fi
     else
 	if [ "$ZOOMED" ]; then
-	    OUTPUTFILE="%DIR%-zoomed"
+	    OUTPUTFILE='`echo %DIR%| sed "s#/#-#"`-zoomed'
 	else
-	    OUTPUTFILE="%DIR%"
+	    OUTPUTFILE='`echo %DIR%| sed "s#/#-#"`'
 	fi
-	$provethem $ADDITIONALARGS --execute "$NASALIBPATH/pvs-scripts/dependencygraph $FORCE $COLLECTIONLABEL $ZOOMORCENTER --svg --rankdir=TB --collection-label=\"$NASALIBDIR=NASALib\" --collection-label=\"lib=PVS Prelude\" --splines=polyline --out=$OUTPUTFILE $ADDITIONALDGARGS $INPUT_FILE; mv $OUTPUTFILE.svg %DIR%/" $DRYRUN --act="Graphing" $INPUT_FILE
+	$provethem $ADDITIONALARGS --execute "$NASALIBPATH/pvs-scripts/dependencygraph $FORCE $COLLECTIONLABEL $ZOOMORCENTER --svg --rankdir=TB --collection-label=\"$NASALIBDIR=NASALib\" --collection-label=\"lib=PVS Prelude\" --splines=polyline --out=$OUTPUTFILE $ADDITIONALDGARGS $INPUT_FILE && mv $OUTPUTFILE.svg %DIR%/" $DRYRUN --act="Plotting" $INPUT_FILE
     fi
 else
   echo "The script 'provethem' could not be located. Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
