Add parameter -pvs-dir to install-scripts

diff --git a/install-scripts b/install-scripts
--- a/install-scripts
+++ b/install-scripts
@@ -1,5 +1,36 @@
 #!/bin/bash
 
+usage() {
+  echo "Installs NASALib scripts. 
+The option -pvs-dir <pvs path> can be used to inform the directory where PVS is installed. This option can be omitted if the directory is in the PVS_DIR or the PATH environment variables."
+}
+
+while [ $# -gt 0 ]
+do
+  case $1 in
+    -h|-help|--help)    
+	usage
+	exit 0;;
+    -pvs-dir)
+	shift
+	P_PVS_DIR=$1;;
+    *)
+	echo "Error: unknown option $1"
+	echo "Type ./install-scripts -h for help"
+	exit 1;;
+  esac
+  shift 
+done 
+
+if [ ! -z "$P_PVS_DIR" ]; then
+    if [ ! -d "$P_PVS_DIR" ]; then
+	echo "Error: $P_PVS_DIR is not a valid directory."
+	exit 1
+    else
+	PVS_DIR=$P_PVS_DIR
+    fi
+fi
+
 if [ ! -d "$PVS_DIR" ]; then
     PVS=`command -v pvs`
     if [ ! -z "$PVS" ]; then
@@ -7,10 +38,19 @@ if [ ! -d "$PVS_DIR" ]; then
 
 	echo "pvs dir assumed to be " $PVS_DIR
     else
-	echo "Error: Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
+	echo "Error: could not locate PVS. 
+Either use the -pvs-dir option to inform the directory where PVS is installed, define an environment variable \$PVS_DIR to point to the PVS directory, or add the PVS directory to the environment variable \$PATH."
 	exit 1
     fi
 fi
+
+if [ ! -f "$PVS_DIR/install-sh" ]; then
+    echo "PVS install script (install-sh) could not be found in the $PVS_DIR directory. 
+Please double check that PVS is installed in this directory and try again."
+    exit 1
+fi
+
+echo "Installing NASALib scripts into $PVS_DIR"
 
 #rsync pvs-patches/proveit.in $PVS_DIR/proveit
 #rsync pvs-patches/provethem.in $PVS_DIR/provethem
