Add default value for pvs-dir to install-scripts

diff --git a/install-scripts b/install-scripts
--- a/install-scripts
+++ b/install-scripts
@@ -38,17 +38,24 @@ if [ ! -d "$PVS_DIR" ]; then
     if [ ! -z "$PVS" ]; then
 	PVS_DIR=${PVS%/*}
 
-	echo "$$PVS_DIR assumed to be $PVS_DIR"
+	echo "Assuming $PVS_DIR as the PVS active installation directory."
     else
-	echo "Error: could not locate PVS. 
-Either use the --pvs-dir option to inform the directory where PVS is installed, define an environment variable \$PVS_DIR to point to the PVS directory, or add the PVS directory to the environment variable \$PATH."
-	exit 1
+	PVS_DIR="../"
+# 	echo "Error: could not locate PVS. 
+# Either use the --pvs-dir option to inform the directory where PVS is installed, define an environment variable \$PVS_DIR to point to the PVS directory, or add the PVS directory to the environment variable \$PATH."
+# 	exit 1
     fi
 fi
 
-if [ ! -f "$PVS_DIR/install-sh" ]; then
-    echo "PVS install script (install-sh) could not be found in the $PVS_DIR directory. 
-Please double check that PVS is installed in this directory and try again."
+if [ ! -f "$PVS_DIR/pvs" ] || [ ! -x "$PVS_DIR/install-sh" ]; then
+    echo "PVS does not seem to be properly installed in '$PVS_DIR'.
+Please use the --pvs-dir <pvs path> option to inform the directory where PVS is installed."
+    exit 1
+fi
+
+if [ ! -f "$PVS_DIR/install-sh" ] || [ ! -x "$PVS_DIR/install-sh" ]; then
+    echo "PVS install script (install-sh) could not be found at '$PVS_DIR'. 
+Please double check that PVS is correctly installed in this directory and try again."
     exit 1
 fi
 
