Modify install-scripts, it no longer assumes pvs location

diff --git a/install-scripts b/install-scripts
--- a/install-scripts
+++ b/install-scripts
@@ -1,8 +1,17 @@
 #!/bin/bash
 
 if [ ! -d "$PVS_DIR" ]; then
-    PVS_DIR=..
+    PVS=`command -v pvs`
+    if [ ! -z "$PVS" ]; then
+	PVS_DIR=${PVS%/*}
+
+	echo "pvs dir assumed to be " $PVS_DIR
+    else
+	echo "Error: Either define \$PVS_DIR to point to the PVS directory or add the PVS directory to the environment variable \$PATH"
+	exit 1
+    fi
 fi
+
 #rsync pvs-patches/proveit.in $PVS_DIR/proveit
 #rsync pvs-patches/provethem.in $PVS_DIR/provethem
 #rsync pvs-patches/pvsio.in $PVS_DIR/pvsio
