Fixed proveit.in

diff --git a/pvs-patches/proveit.in b/pvs-patches/proveit.in
--- a/pvs-patches/proveit.in
+++ b/pvs-patches/proveit.in
@@ -185,11 +185,15 @@ append() {
 cleanup() {
   if [ "$CLEAN" ]
   then 
+    if [ "$LOGFILE" ];
+    then
+      LOGFILE_RELATIVE_PATH="$OUTDIR/$LOGFILE"
+    fi
     if [ -z "$QUIET" ]
     then
-      echo "Removing $PVSCONTEXT/.pvscontext $PVSCONTEXT/$PVSBIN/ $OUTFILE $LOGFILE"
+      echo "Removing $PVSCONTEXT/.pvscontext $PVSCONTEXT/$PVSBIN/ $OUTDIR/$OUTFILE $LOGFILE_RELATIVEPATH"
     fi
-    rm -r -f $PVSCONTEXT/.pvscontext $PVSCONTEXT/$PVSBIN/*.* $OUTFILE $LOGFILE
+    rm -r -f $PVSCONTEXT/.pvscontext $PVSCONTEXT/$PVSBIN/*.* $OUTDIR/$OUTFILE $LOGFILE_RELATIVEPATH
   fi
 }
 
@@ -614,12 +618,14 @@ do
 	  fi
 	  shift;;
     -d|-dir|--dir)           
-	  if [ -d "$2" ]; then
-	      OUTDIR=$2
-          else
- 	      echo "Error: $2 is not a directory"
-	      exit 1
-	  fi
+      OUTDIR=$2
+      if [ ! -e "$OUTDIR" ]; then
+        mkdir $OUTDIR
+      fi
+      if [ ! -d "$OUTDIR" ]; then
+        echo "Error: $OUTDIR is not a directory"
+        exit 1
+      fi
 	  shift;;
     -t|-top|--top)           
 	  TOP=$2
