proveit: pvs is searched in the proveit folder

diff --git a/pvs-patches/scripts/proveit b/pvs-patches/scripts/proveit
--- a/pvs-patches/scripts/proveit
+++ b/pvs-patches/scripts/proveit
@@ -12,7 +12,7 @@
 # is claimed in the United States under Title 17, U.S.Code. All Other
 # Rights Reserved.
 #
-# Mariano Moscato (04/26/2021)
+# Mariano Moscato (08/02/2022)
 # National Institute of Aerospace
 #
 # Script for batch proving in PVS 
@@ -24,17 +24,28 @@ PVSPATH=@PVSPATH@
 # Nothing below this line should need modification
 #
 
-if ! type "$PVSPATH/pvs" > /dev/null 2>&1  || ! VERSION=$($PVSPATH/pvs -raw -E '(format t "~&~%PVSIOVERSION ~a~%~%" *prooflite-version*)(bye)' 2> /dev/null | grep PVSIOVERSION | sed 's/^.*PVSIOVERSION \(.*\)$/\1/g') ; then
-    TYPE_OUTPUT=`type pvs`;
+# if ! type "$PVSPATH/pvs" > /dev/null 2>&1  || ! VERSION=$($PVSPATH/pvs -raw -E '(format t "~&~%PVSIOVERSION ~a~%~%" *prooflite-version*)(bye)' 2> /dev/null | grep PVSIOVERSION | sed 's/^.*PVSIOVERSION \(.*\)$/\1/g') ; then
+
+type "$PVSPATH/pvs"  > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+    PVSPATH=$PVSPATH/
+else
+    type pvs  > /dev/null 2>&1
     if [ $? -eq 0 ]; then
 	PVSPATH="" # pvs is in the system path, then no path information is needed
     else
-	printf "Error: PVS could not be located. Add it to the system path or run install-scripts in the PVS folder.\n"
-	exit 1;
+	PVSPATH=`dirname $0`
+	type "$PVSPATH/pvs"  > /dev/null 2>&1
+	if [ $? -eq 0 ]; then
+	    PVSPATH=$PVSPATH/
+	else
+	    printf "Error: PVS could not be located. Add it to the system path or run install-scripts in the PVS folder.\n"
+	    exit 1;
+	fi
     fi
-else
-    PVSPATH=$PVSPATH/
 fi
+
+VERSION=$("$PVSPATH"pvs -raw -E '(format t "~&~%PVSIOVERSION ~a~%~%" *prooflite-version*)(bye)' 2> /dev/null | grep PVSIOVERSION | sed 's/^.*PVSIOVERSION \(.*\)$/\1/g')
 
 PVS_RETURN_VALUE_MISSED_FORMS=142 # PVS' return value indicating missed (ie, not proved) formulas
 
