Add md output for proveit status

diff --git a/pvs-patches/scripts/proveit b/pvs-patches/scripts/proveit
--- a/pvs-patches/scripts/proveit
+++ b/pvs-patches/scripts/proveit
@@ -333,6 +333,7 @@ OPTIONS
    --version           print version information and exit
    -w|--write-scripts  write proofs as prooflite scripts into separate files (disabled by default,
                        this option is omitted in typecheck-only mode.)
+   --summary-mode [md] alternative summary mode
 
 SEE ALSO
   provethem -- for iterating proveit on a list of directories
@@ -626,6 +627,9 @@ proveit() {
 	  if [ "$LISPDEPENDENCIES" != "nil" ]; then
 	      echo "Saving theory dependencies ($LISPDEPENDENCIES) in directory pvsbin"
 	  fi
+	  if [ "$LISPALTSUMMARIESMODE" != "nil" ]; then
+	      echo "Summaries will be reported in alternative format ($LISPALTSUMMARIESMODE)."
+	  fi
 	  if [ "$LISPSCRIPTS" != "t" ]; then
 	      echo "ProofLite scripts won't be installed"
 	  fi 
@@ -667,7 +671,7 @@ proveit() {
 	  export PROVEITPVSFILE="$PVSFILE"
       else
  	  export PROVEITPVSFILE=""
-      fi
+      fi      
       export PROVEITLISPIMPORT="$LISPIMPORT"
       export PROVEITLISPSCRIPTS="$LISPSCRIPTS"
       export PROVEITLISPWRITESCRIPTS="$LISPWRITESCRIPTS"
@@ -678,6 +682,7 @@ proveit() {
       export PROVEITLISPTXTPROOFS="$LISPTXTPROOFS"
       export PROVEITLISPTEXPROOFS="$LISPTEXPROOFS"
       export PROVEITLISPDEPENDENCIES="$LISPDEPENDENCIES"
+      export PROVEITLISPALTSUMMARIESMODE="$LISPALTSUMMARIESMODE"
       export PROVEITLISPPRELUDEXT="`list_to_lisp $PRELUDEXT`"
       export PROVEITLISPDISABLE="`list_to_lisp $DISABLE`"
       export PROVEITLISPENABLE="`list_to_lisp $ENABLE`"
@@ -686,33 +691,38 @@ proveit() {
       export PROVEITLISPAUTOFIX="$LISPAUTOFIX"
       export PROVEITLISPRETRYWITHTCCS="$LISPRETRYWITHTCCS"
       export PROVEITLISPDEFAULTPROOFSCRIPT="$LISPDEFAULTPROOFSCRIPT"
+
+      export PROVEITLISPOUTDIR=$dir
+      export PROVEITLISPOUTBASENAME=$BASEOUT
       
       if [ "$DEBUG" ]; then
-	  echo "QUIET: $QUIET"
-	  echo "PROVEITVERSION: $VERSION"
-	  echo "OUTFILE: $OUTFILE"
-	  echo "LOGFILE: $LOGFILE"
-	  echo "PROVEITARG: $PROVEITARG"
-	  echo "PROVEITPVSCONTEXT: $PROVEITPVSCONTEXT"
-	  echo "PROVEITPVSFILE: $PROVEITPVSFILE"
-	  echo "PROVEITLISPIMPORT: $PROVEITLISPIMPORT"
-	  echo "PROVEITLISPSCRIPTS: $PROVEITLISPSCRIPTS"
-	  echo "PROVEITLISPWRITESCRIPTS: $PROVEITLISPWRITESCRIPTS"
-	  echo "PROVEITLISPTRACES: $PROVEITLISPTRACES"
-	  echo "PROVEITLISPFORCE: $PROVEITLISPFORCE" 
-	  echo "PROVEITLISPAUTOTOP: $LISPAUTOTOP"
-	  echo "PROVEITLISPTYPECHECK: $PROVEITLISPTYPECHECK"
-	  echo "PROVEITLISPTXTPROOFS: $PROVEITLISPTXTPROOFS"
-	  echo "PROVEITLISPTEXPROOFS: $PROVEITLISPTEXPROOFS"
-	  echo "PROVEITLISPDEPENDENCIES: $PROVEITLISPDEPENDENCIES"
-	  echo "PROVEITLISPPRELUDEXT: $PROVEITLISPPRELUDEXT"
-	  echo "PROVEITLISPDISABLE: $PROVEITLISPDISABLE"
-	  echo "PROVEITLISPENABLE: $PROVEITLISPENABLE"
-	  echo "PROVEITLISPTHFS: $PROVEITLISPTHFS"
-	  echo "PROVEITLISPTHEORIES: $PROVEITLISPTHEORIES"
-	  echo "PROVEITLISPAUTOFIX: $PROVEITLISPAUTOFIX"
-	  echo "PROVEITLISPRETRYWITHTCCS: $PROVEITLISPRETRYWITHTCCS"
-	  echo "PROVEITLISPDEFAULTPROOFSCRIPT: $PROVEITLISPDEFAULTPROOFSCRIPT"
+	  export DEBUG
+	  echo "QUIET=$QUIET"
+	  echo "PROVEITVERSION=$VERSION"
+	  echo "OUTFILE=$OUTFILE"
+	  echo "LOGFILE=$LOGFILE"
+	  echo "export PROVEITARG=$PROVEITARG"
+	  echo "export PROVEITPVSCONTEXT=$PROVEITPVSCONTEXT"
+	  echo "export PROVEITPVSFILE=$PROVEITPVSFILE"
+	  echo "export PROVEITLISPIMPORT=$PROVEITLISPIMPORT"
+	  echo "export PROVEITLISPSCRIPTS=$PROVEITLISPSCRIPTS"
+	  echo "export PROVEITLISPWRITESCRIPTS=$PROVEITLISPWRITESCRIPTS"
+	  echo "export PROVEITLISPTRACES=$PROVEITLISPTRACES"
+	  echo "export PROVEITLISPFORCE=$PROVEITLISPFORCE" 
+	  echo "export PROVEITLISPAUTOTOP=$LISPAUTOTOP"
+	  echo "export PROVEITLISPTYPECHECK=$PROVEITLISPTYPECHECK"
+	  echo "export PROVEITLISPTXTPROOFS=$PROVEITLISPTXTPROOFS"
+	  echo "export PROVEITLISPTEXPROOFS=$PROVEITLISPTEXPROOFS"
+	  echo "export PROVEITLISPDEPENDENCIES=$PROVEITLISPDEPENDENCIES"
+	  echo "export PROVEITLISPALTSUMMARIESMODE=$PROVEITLISPALTSUMMARIESMODE"
+	  echo "export PROVEITLISPPRELUDEXT=$PROVEITLISPPRELUDEXT"
+	  echo "export PROVEITLISPDISABLE=$PROVEITLISPDISABLE"
+	  echo "export PROVEITLISPENABLE=$PROVEITLISPENABLE"
+	  echo "export PROVEITLISPTHFS=$PROVEITLISPTHFS"
+	  echo "export PROVEITLISPTHEORIES=$PROVEITLISPTHEORIES"
+	  echo "export PROVEITLISPAUTOFIX=$PROVEITLISPAUTOFIX"
+	  echo "export PROVEITLISPRETRYWITHTCCS=$PROVEITLISPRETRYWITHTCCS"
+	  echo "export PROVEITLISPDEFAULTPROOFSCRIPT=$PROVEITLISPDEFAULTPROOFSCRIPT"
       fi
       
       if [ $PVSTIMEOUT ]; then
@@ -846,6 +856,14 @@ do
 	    shift
 	else
 	    echo "Error: --dependencies option must be followed by the options 'relative' or 'fullpath'. (See proveit --help for details.)"
+	    exit 1
+	fi;;
+    -summary-mode|--summary-mode)
+	if echo $2 | grep -qE '^md$'; then
+	    LISPALTSUMMARIESMODE=md
+	    shift
+	else
+	    echo "Error: --summary-mode option must be followed by the option 'md'. (See proveit --help for details.)"
 	    exit 1
 	fi;;
     --timeout)
